export const clients = [
  {
    id: 1,
    navn: 'Jonas Yaich',
    status: 'Aktiv',
    email: 'Jona223j@gmail.com',
    telefon: '',
    cpr: '',
    adresse: 'Rugmarken 6',
    by: 'Rødekro',
    postnummer: '6230',
    land: 'Denmark',
  },
  {
    id: 2,
    navn: 'Anna Hansen',
    status: 'Aktiv',
    email: 'anna.hansen@email.com',
    telefon: '+45 12 34 56 78',
    cpr: '010190-1234',
    adresse: 'Hovedgaden 42',
    by: 'København',
    postnummer: '2100',
    land: 'Denmark',
  },
  {
    id: 3,
    navn: 'Peter Nielsen',
    status: 'Inaktiv',
    email: 'peter.n@email.com',
    telefon: '+45 98 76 54 32',
    cpr: '150285-5678',
    adresse: 'Skovvej 15',
    by: 'Aarhus',
    postnummer: '8000',
    land: 'Denmark',
  },
  {
    id: 4,
    navn: 'Maria Andersen',
    status: 'Aktiv',
    email: 'maria.a@email.com',
    telefon: '+45 11 22 33 44',
    cpr: '200392-9012',
    adresse: 'Strandvejen 88',
    by: 'Odense',
    postnummer: '5000',
    land: 'Denmark',
  },
];
